export const Gents={
    title:"Gents Fashion",
    image1:"Images/Men/1.jpg",
    image2:"Images/Men/2.jpg",
    image3:"Images/Men/3.jpg",
    image4:"Images/Men/4.jpg",
    image5:"Images/Men/5.jpg",
    image6:"Images/Men/6.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}
export const Ladies={
    title:"Ladies Fashion",
    image1:"Images/Woman/1.jpg",
    image2:"Images/Woman/2.jpg",
    image3:"Images/Woman/3.jpg",
    image4:"Images/Woman/4.jpg",
    image5:"Images/Woman/5.jpg",
    image6:"Images/Woman/6.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}